server:
  port: 9090
spring:
  application:
    name: auth_server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/weifuwu_security?serverTimezone=GMT%2B8
    username: root
    password: root
  session:
    timeout: 2592000